// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaJvRWzUkT14KmZPhGy4P3QFyQKKAMBBM',
    appId: '1:225365158647:android:3128422c4aa3fbb98ec1f2',
    messagingSenderId: '225365158647',
    projectId: 'characterexplorer-ccbab',
    storageBucket: 'characterexplorer-ccbab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj---9vbM3ofoO6P4eHK9kK0iAZmGM3K8',
    appId: '1:225365158647:ios:4332cf5533e9e47c8ec1f2',
    messagingSenderId: '225365158647',
    projectId: 'characterexplorer-ccbab',
    storageBucket: 'characterexplorer-ccbab.firebasestorage.app',
    androidClientId: '225365158647-o1gsfl7a03s4a4udphbbdvsvnvteuqbf.apps.googleusercontent.com',
    iosClientId: '225365158647-t0dd5a5t38t9dr4ep2vniknqn812evi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.characterExplorer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrEnHU9F2hCPMdyTSQxKAfskR0Y9AZnpk',
    appId: '1:225365158647:web:b76534d805f4983c8ec1f2',
    messagingSenderId: '225365158647',
    projectId: 'characterexplorer-ccbab',
    authDomain: 'characterexplorer-ccbab.firebaseapp.com',
    storageBucket: 'characterexplorer-ccbab.firebasestorage.app',
    measurementId: 'G-Z8MH3JVW7H',
  );

}